### ISSUE TITLE
Missing description on Collection / Bundle page

### ISSUE THREAD

**Issue by jordanpadams** [sbn-psi/archive-viewer#2]
https://sbnarchivedemo.psi.edu/?dataset=urn%3Anasa%3Apds%3Ainsight_cameras%3Adata

The description in the registry is not very helpful:

> Collection of DATA products.

But since there is a description available in the registry, maybe the viewer would fallback to that since one has not been specified via the archive-loader?

**Comment by mdrum** [comment]
This was an actual bug, thanks! I had done some field trimming earlier and dataset description got removed; it's back in there now, and displaying correctly.
